---
title: "Case study 2"
author: "IsabelDing"
date: "5/1/2020"
output: html_document
---

```{r include=FALSE}
library(dplyr)
library(gapminder)
library(tidyverse)
noKuwait <- gapminder %>%  filter(country != "Kuwait")

firstPlot <- 
  ggplot(data = noKuwait) +
  geom_point(mapping = aes(x = lifeExp, y = gdpPercap, size = pop/100000, color = continent)) +
  labs(x = "Life Expectancy", y = "GDP per capita") +
  scale_y_continuous(trans = "sqrt") +
  facet_wrap(~ year, nrow = 1) + 
  theme_bw() 

firstPlot
ggsave("first plot.pdf", width = 15, units = "in")

```

```{r include=FALSE}
library(dplyr)
secondPlot <-
  ggplot(data = noKuwait) +
  geom_line(mapping = aes(x = year, y = gdpPercap, group = country, color = continent)) +
  geom_point(mapping = aes(x = year, y = gdpPercap, group = country, color = continent, size = pop/100000)) + 
  geom_line(data = noKuwait 
            %>% group_by(continent, year)
            %>% summarize(mean = weighted.mean(gdpPercap, pop), 
                          populationSum = sum(as.numeric(pop))),
            mapping = aes(x = year, y = mean, group = continent, color = "blank")) +
  geom_point(data = noKuwait
             %>% group_by(continent, year)
             %>% summarize(mean = weighted.mean(gdpPercap, pop),
                           populationSum = sum(as.numeric(pop))),
             mapping = aes(x = year, y = mean, size = populationSum/100000, group = continent, color = "blank")) +
  facet_wrap(~ continent, nrow = 1) +
  theme_bw() +
  labs(x = "Year", y = "GDP per capita")


secondPlot
  

```
